ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM lyfta_app;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM lyfta_app;
REVOKE USAGE ON SCHEMA public FROM lyfta_app;
REVOKE ALL PRIVILEGES ON DATABASE lyfta_identity FROM lyfta_app;
DROP ROLE IF EXISTS lyfta_app;
